### ISSUE TITLE
JNA benchmark in direct mapped mode

### ISSUE THREAD

**Issue by hjohn** [zakgof/java-native-benchmark#1]
Did you also benchmark JNA in direct mapping mode?  It is said to approach the speed of JNI.  See here: https://github.com/java-native-access/jna/blob/master/www/DirectMapping.md

**Comment by zakgof** [comment]
Nice suggestion, let me try this

**Comment by zakgof** [comment]
Added JNA direct benchmark, however, it did not show any improved performance for this particular case

**Comment by hjohn** [comment]
Thanks, very interesting results.
